//
//  EnumGen.swift
//  WebComposeTest
//
//  Created by Ryu on 2022/07/24.
//

import Foundation


open class EnumGen {
    
    enum EnumGenError: LocalizedError {
        case invalidName
        case failedToCreateFile
        
        var errorDescription: String? {
            switch self {
            case .invalidName:
                return "enumName must be a string of one or more characters."
            case .failedToCreateFile:
                return "Failed to create file"
            }
        }
    }
    
    private let reservedWords = [
        "actor",
        "async",
        "async",
        "await",
        "class",
        "deinit",
        "enum",
        "extension",
        "fileprivate",
        "func",
        "import",
        "init",
        "inout",
        "internal",
        "let",
        "open",
        "operator",
        "precedencegroup",
        "private",
        "protocol",
        "public",
        "static",
        "some",
        "struct",
        "subscript",
        "typealias",
        "associatedtype",
        "var",
        "break",
        "case",
        "continue",
        "default",
        "defer",
        "do",
        "else",
        "fallthrough",
        "for",
        "guard",
        "if",
        "in",
        "repeat",
        "return",
        "switch",
        "where",
        "while",
        "as",
        "any",
        "Any",
        "catch",
        "false",
        "is",
        "nil",
        "rethrows",
        "super",
        "self",
        "Self",
        "throw",
        "throws",
        "true",
        "try",
        "#available",
        "#unavailable",
        "#colorLiteral",
        "#column",
        "#if",
        "#else",
        "#elseif",
        "#endif",
        "#error",
        "#file",
        "#fileID",
        "#filePath",
        "#fileLiteral",
        "#function",
        "#imageLiteral",
        "#keyPath",
        "#line",
        "#selector",
        "#sourceLocation",
        "#warning",
        "#dsohandle",
        "assignment",
        "associativity",
        "convenience",
        "dynamic",
        "didSet",
        "final",
        "get",
        "protocol",
        "infix",
        "indirect",
        "lazy",
        "left",
        "mutating",
        "none",
        "nonisolated",
        "nonmutating",
        "optional",
        "override",
        "postfix",
        "prefix",
        "Protocol",
        "required",
        "right",
        "set",
        "protocol",
        "Type",
        "unowned",
        "unowned(safe)",
        "unowned(unsafe)",
        "weak",
        "willSet"
    ]
    
    public let strings: [String]
    public let enumName: String
    public let fileURL: URL
    
    public init(strings: [String], enumName: String, path: String = #file) throws {
        guard enumName != "" else { throw EnumGenError.invalidName }
        
        self.strings = strings
        self.enumName = enumName
        
        let originalPath = URL(fileURLWithPath: path)
        let directoryPath = originalPath.isDirectory ? originalPath : originalPath.deletingLastPathComponent()
        self.fileURL = directoryPath
            .appendingPathComponent(enumName, isDirectory: false)
            .appendingPathExtension("swift")
    }
    
    open func generate() throws {
        let enumString = createEnumString()
        
        if FileManager.default.createFile(atPath: fileURL.path, contents: enumString.data(using: .utf8)) {
            print("Creation of \(enumName) in \(fileURL.path) is completed")
        }
        else {
            throw EnumGenError.failedToCreateFile
        }
    }
    
    private func createEnumString() -> String {
        var enumString =
        """
        // This is a generated file.
        // Generated by EnumGen, see https://github.com/Ryu0118/EnumGen
        """
        let importString = "import Foundation"
        let enumDefinition = "enum \(enumName) {"
        
        enumString.newLine()
        enumString.addLine(importString)
        enumString.newLine()
        enumString.addLine(enumDefinition)
        
        strings.forEach {
            if reservedWords.contains($0) {
                enumString.addLine("case `\($0)`", indentCount: 1)
            }
            else {
                enumString.addLine("case \($0)", indentCount: 1)
            }
        }
        
        enumString.addLine("}")
        
        return enumString
    }
    
}
